

build:
  version: "3.0"

accounts:
  message: "Welcome to Bank accounts related local APIs in prod"
  contactDetails:
    name: "John Doe - prod"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345